# Generated by Django 5.0.6 on 2024-07-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField()),
                ('questions_attempted', models.CharField()),
                ('percentage_score', models.CharField()),
            ],
        ),
    ]
