# Generated by Django 5.0.6 on 2024-07-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='optionC',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='optionD',
            field=models.CharField(blank=True, null=True),
        ),
    ]
