# Generated by Django 5.0.6 on 2024-07-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0002_alter_question_optionc_alter_question_optiond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, null=True),
        ),
    ]
