# Generated by Django 5.0.6 on 2024-07-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0003_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
